import {
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  CloudCog,
  Code2,
  DatabaseZap,
  GitBranch,
  Globe2,
  GraduationCap,
  Link,
  Mail,
  MapPin,
  MessageCircle,
  Rocket,
  Smartphone,
} from "lucide-react";
import type { ContactMethod, Project, SkillCategory, Stat, TimelineItem } from "@/types/portfolio";
import { formatWhatsappLink } from "@/lib/utils";

export const profile = {
  name: "Hector Rosales Ortiz",
  title: "Senior AI & Full Stack Engineer",
  subtitle: "Building AI-Powered Products, Enterprise Platforms, and Scalable Digital Experiences.",
  email: "mern2025@outlook.com",
  telegram: "@yesteru",
  whatsapp: "+1 (856) 495-1739",
  linkedin: "https://www.linkedin.com/in/héctor-rosales-ortiz-69a9607a/",
  country: "Mexico",
};

export const stats: Stat[] = [
  { value: "10+", label: "Years Experience" },
  { value: "50+", label: "Projects" },
  { value: "AI", label: "Specialist" },
  { value: "Full Stack", label: "Expert" },
];

export const capabilities = [
  {
    title: "AI Product Engineering",
    description: "LLM-powered workflows, RAG platforms, agentic systems, prompt strategies, and production-grade AI assistants.",
    icon: BrainCircuit,
  },
  {
    title: "Technical Leadership",
    description: "Architecture decisions, mentoring, code quality, delivery strategy, and enterprise stakeholder alignment.",
    icon: BriefcaseBusiness,
  },
  {
    title: "Cloud Architecture",
    description: "Scalable platforms across AWS, Azure, and GCP with containerized workloads and CI/CD automation.",
    icon: CloudCog,
  },
  {
    title: "End-to-End Platforms",
    description: "Modern web, mobile, backend, API, data, and DevOps delivery for high-growth digital products.",
    icon: Rocket,
  },
];

export const skillCategories: SkillCategory[] = [
  {
    title: "AI & LLM",
    description: "Applied AI systems that combine model reasoning, retrieval, tools, and product UX.",
    level: 96,
    icon: Bot,
    skills: ["OpenAI", "LangChain", "RAG", "AI Agents", "Prompt Engineering", "Vector Databases", "LlamaIndex"],
  },
  {
    title: "Frontend",
    description: "Premium interfaces with strong accessibility, animation, and product polish.",
    level: 95,
    icon: Code2,
    skills: ["React", "Next.js", "TypeScript", "Angular", "Tailwind", "Material UI"],
  },
  {
    title: "Backend",
    description: "Secure, scalable APIs and services for enterprise-grade systems.",
    level: 92,
    icon: DatabaseZap,
    skills: ["Node.js", "Python", "FastAPI", "Spring Boot", "GraphQL", "REST APIs"],
  },
  {
    title: "Mobile",
    description: "High-performance mobile experiences across Flutter, React Native, and native ecosystems.",
    level: 92,
    icon: Smartphone,
    skills: ["Flutter", "React Native", "Swift", "Kotlin"],
  },
  {
    title: "Cloud & DevOps",
    description: "Reliable delivery pipelines, observability-ready deployments, and cloud-native architecture.",
    level: 90,
    icon: CloudCog,
    skills: ["AWS", "Azure", "GCP", "Docker", "Kubernetes", "CI/CD"],
  },
];

export const timeline: TimelineItem[] = [
  {
    company: "Freelance",
    role: "Senior AI & Full Stack Engineer",
    location: "Remote",
    period: "January 2024 - Present",
    technologies: [
      "Python",
      "FastAPI",
      "Next.js",
      "React",
      "TypeScript",
      "OpenAI API",
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "Pinecone",
      "AWS",
      "Azure",
      "Docker",
      "Kubernetes",
    ],
    responsibilities: [
      "Developed AI-powered applications and enterprise automation platforms.",
      "Built RAG systems, AI assistants, and multi-agent workflows.",
      "Integrated LLM technologies into existing business systems.",
      "Designed cloud-native AI infrastructure and deployment pipelines.",
      "Consulted clients on AI strategy and implementation.",
    ],
    achievements: [
      "Delivered production-ready AI business solutions.",
      "Built enterprise knowledge management and search systems.",
      "Reduced operational costs through intelligent automation.",
      "Successfully launched AI-powered SaaS products.",
    ],
  },
  {
    company: "Freelance",
    role: "Senior Full Stack Developer",
    location: "Remote",
    period: "November 2020 - December 2023",
    technologies: [
      "React",
      "Next.js",
      "React Native",
      "Node.js",
      "NestJS",
      "TypeScript",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "AWS",
      "Docker",
    ],
    responsibilities: [
      "Designed and developed custom web and mobile applications for startups and SMBs.",
      "Built SaaS platforms, e-commerce systems, logistics platforms, and CRM solutions.",
      "Led architecture and technical decision-making.",
      "Managed deployments and cloud infrastructure.",
      "Worked directly with clients throughout the project lifecycle.",
    ],
    achievements: [
      "Delivered 20+ successful client projects.",
      "Built scalable systems serving thousands of users.",
      "Established long-term client relationships through consistent delivery.",
    ],
  },
  {
    company: "Unosquare",
    role: "Full Stack & Mobile Developer",
    location: "Guadalajara, Jalisco, Mexico",
    period: "January 2019 - October 2020",
    technologies: ["React", "React Native", "TypeScript", "Node.js", "Express.js", "PostgreSQL", "Firebase", "AWS"],
    responsibilities: [
      "Developed web and mobile applications for enterprise clients.",
      "Built RESTful APIs and backend services.",
      "Implemented reusable frontend components using React.",
      "Developed cross-platform mobile applications using React Native.",
      "Participated in architecture discussions and code reviews.",
      "Assisted with cloud deployments and CI/CD pipelines.",
    ],
    achievements: [
      "Successfully delivered multiple production applications.",
      "Improved engineering productivity through reusable components.",
      "Contributed to scalable cloud-native solutions.",
    ],
  },
  {
    company: "Blue People",
    role: "Junior Web Developer",
    location: "Mexico City, Mexico",
    period: "February 2016 - November 2018",
    technologies: ["HTML", "CSS", "JavaScript", "jQuery", "PHP", "MySQL", "Bootstrap", "Git"],
    responsibilities: [
      "Developed responsive websites and internal business applications.",
      "Implemented frontend interfaces from UI/UX designs.",
      "Built backend functionality and database integrations.",
      "Performed maintenance, debugging, and performance optimization.",
      "Collaborated with project managers, designers, and senior developers.",
      "Participated in Agile development processes.",
    ],
    achievements: [
      "Delivered multiple web solutions for business clients.",
      "Improved website performance and maintainability.",
      "Built a strong foundation in full-stack web development.",
    ],
  },
];

export const projects: Project[] = [
  {
    title: "Enterprise AI Applications",
    role: "Senior AI & Full Stack Engineer",
    company: "Globant",
    location: "Remote, Mexico",
    period: "January 2024 - Present",
    companyUrl: "https://www.globant.com/",
    description: "Enterprise AI applications using Large Language Models, RAG systems, AI assistants, and OpenAI-based workflow integrations.",
    stack: ["Python", "FastAPI", "React", "Next.js", "TypeScript", "OpenAI API", "LangChain", "AWS", "Azure", "Kubernetes"],
    impact: "Delivered production-ready AI-powered business solutions and enterprise knowledge management systems powered by LLMs.",
    featured: true,
    imageUrls: ["/assets/projects/globant-ai-pods.png", "/assets/projects/globant-insights.png"],
    responsibilities: [
      "Developed enterprise AI applications using Large Language Models.",
      "Built Retrieval-Augmented Generation (RAG) systems and AI assistants.",
      "Integrated OpenAI-based solutions into enterprise workflows.",
      "Designed scalable cloud-native applications.",
      "Led technical architecture discussions and code reviews.",
      "Mentored engineering teams on AI adoption and implementation.",
    ],
    achievements: [
      "Delivered production-ready AI-powered business solutions.",
      "Improved operational efficiency through intelligent automation.",
      "Built enterprise knowledge management systems powered by LLMs.",
    ],
  },
  {
    title: "Food Delivery & Super App Platform",
    role: "Full Stack Developer",
    company: "Remote",
    location: "Mexico",
    period: "May 2025 - July 2025",
    description: "A modern food delivery and super app platform inspired by large-scale on-demand ecosystems, with restaurant discovery, promotional sections, dynamic content modules, and mobile-first UX.",
    stack: ["React", "Next.js", "Tailwind CSS", "TypeScript", "Swiper", "Vercel"],
    impact: "Delivered a production-ready food delivery platform with modern UX standards, reusable frontend architecture, and optimized Lighthouse performance.",
    demoUrl: "https://web.didiglobal.com/mx/food",
    featured: true,
    imageUrls: ["/assets/projects/didi-hero.png", "/assets/projects/didi-promos.png", "/assets/projects/didi-cities.png"],
    responsibilities: [
      "Designed and implemented scalable frontend architecture using React and Next.js.",
      "Built reusable UI components and mobile-first interfaces using Tailwind CSS.",
      "Integrated Swiper-based promotional carousels and interactive content sections.",
      "Managed deployment pipelines and production hosting using Vercel.",
    ],
    achievements: [
      "Created reusable frontend architecture for future feature development.",
      "Improved SEO, rendering performance, and page loading speed through Next.js optimization techniques.",
      "Established scalable development patterns for future platform growth.",
    ],
  },
  {
    title: "Rappi Consumer Platform",
    role: "Senior Mobile & Full Stack Engineer",
    company: "Rappi",
    location: "Mexico City, Mexico",
    period: "April 2021 - December 2023",
    companyUrl: "https://www.rappi.com.mx/",
    links: [
      { label: "App Store", href: "https://apps.apple.com/co/app/rappi-pide-todo-en-minutos/id984044296" },
      { label: "Google Play", href: "https://play.google.com/store/apps/details?id=com.grability.rappi" },
    ],
    description: "Large-scale consumer mobile and web platform work across ordering, logistics, React Native initiatives, performance, monitoring, and analytics.",
    stack: ["React Native", "React", "TypeScript", "Node.js", "GraphQL", "PostgreSQL", "AWS", "Kotlin", "Swift"],
    impact: "Contributed to applications serving millions of users while improving mobile application performance, stability, and shared component adoption.",
    featured: true,
    imageUrls: ["/assets/projects/rappi-restaurants.png", "/assets/projects/rappi-super.png", "/assets/projects/rappi-mobile.png"],
    responsibilities: [
      "Developed mobile and web features for large-scale consumer applications.",
      "Participated in React Native platform initiatives.",
      "Built backend services supporting logistics and ordering systems.",
      "Collaborated with distributed engineering teams across Latin America.",
      "Improved performance, reliability, and maintainability of applications.",
      "Implemented monitoring and analytics solutions.",
    ],
    achievements: [
      "Contributed to applications serving millions of users.",
      "Improved mobile application performance and stability.",
      "Developed reusable components adopted across multiple teams.",
      "Successfully delivered large-scale product releases.",
    ],
  },
  {
    title: "Enterprise SaaS Products",
    role: "Senior Full Stack Engineer",
    company: "Wizeline",
    location: "Guadalajara, Mexico",
    period: "January 2019 - March 2021",
    companyUrl: "https://www.wizeline.ai/",
    description: "Enterprise SaaS products for international clients, including scalable frontend and backend architectures, microservices, and cloud-native applications.",
    stack: ["React", "TypeScript", "Node.js", "GraphQL", "GCP", "Kubernetes", "PostgreSQL"],
    impact: "Delivered digital transformation projects, improved engineering efficiency through reusable frameworks, and reduced deployment times with CI/CD automation.",
    imageUrls: ["/assets/projects/wizeline-home.png", "/assets/projects/wizeline-ai.png"],
    responsibilities: [
      "Developed enterprise SaaS products for international clients.",
      "Designed scalable frontend and backend architectures.",
      "Built microservices and cloud-native applications.",
      "Mentored junior engineers and conducted code reviews.",
      "Participated in Agile product development.",
    ],
    achievements: [
      "Delivered multiple digital transformation projects.",
      "Improved engineering efficiency through reusable frameworks.",
      "Reduced deployment times using CI/CD automation.",
    ],
  },
  {
    title: "Enterprise Banking & Retail Solutions",
    role: "Full Stack Developer",
    company: "Softtek",
    location: "Mexico City, Mexico",
    period: "January 2016 - December 2018",
    companyUrl: "https://www.softtek.com",
    description: "Enterprise software solutions for banking and retail clients, including REST APIs, backend services, responsive interfaces, and legacy modernization.",
    stack: ["Java", "Spring Boot", "AngularJS", "JavaScript", "MySQL", "SQL Server"],
    impact: "Delivered multiple enterprise projects, improved system performance, and contributed to modernization of legacy applications.",
    imageUrls: ["/assets/projects/softtek-home.png", "/assets/projects/softtek-experience.png"],
    responsibilities: [
      "Developed enterprise software solutions for banking and retail clients.",
      "Created REST APIs and backend services.",
      "Built responsive web interfaces.",
      "Optimized database performance and application reliability.",
      "Participated in Agile software development teams.",
    ],
    achievements: [
      "Successfully delivered multiple enterprise projects.",
      "Improved system performance through code optimization.",
      "Contributed to modernization of legacy applications.",
    ],
  },
];

export const contactMethods: ContactMethod[] = [
  {
    label: "Email",
    value: profile.email,
    href: `mailto:${profile.email}`,
    icon: Mail,
  },
  {
    label: "Telegram",
    value: profile.telegram,
    href: "https://t.me/yesteru",
    icon: MessageCircle,
  },
  {
    label: "WhatsApp",
    value: profile.whatsapp,
    href: formatWhatsappLink(profile.whatsapp),
    icon: MessageCircle,
  },
  {
    label: "LinkedIn",
    value: "Hector Rosales Ortiz",
    href: profile.linkedin,
    icon: Link,
  },
  {
    label: "Country",
    value: profile.country,
    icon: MapPin,
  },
];

export const socialLinks = [
  { label: "LinkedIn", href: profile.linkedin, icon: Link },
  { label: "GitHub", href: "https://github.com/", icon: GitBranch },
  { label: "Global", href: "#projects", icon: Globe2 },
];

export const education = {
  institution: "Instituto Politecnico Nacional",
  url: "https://www.ipn.mx/",
  degree: "Bachelor's Degree",
  field: "Networking of Computer Systems",
  period: "2010 - 2015",
  icon: GraduationCap,
};
